/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.MstRoll;
import com.example.jooq.tables.User;
import com.example.jooq.tables.records.MstRollRecord;
import com.example.jooq.tables.records.UserRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * main.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MstRollRecord> KEY_MST_ROLL_ID_UNIQUE = Internal.createUniqueKey(MstRoll.MST_ROLL, DSL.name("KEY_mst_roll_id_UNIQUE"), new TableField[] { MstRoll.MST_ROLL.ID }, true);
    public static final UniqueKey<MstRollRecord> KEY_MST_ROLL_LABEL_UNIQUE = Internal.createUniqueKey(MstRoll.MST_ROLL, DSL.name("KEY_mst_roll_label_UNIQUE"), new TableField[] { MstRoll.MST_ROLL.LABEL }, true);
    public static final UniqueKey<MstRollRecord> KEY_MST_ROLL_PRIMARY = Internal.createUniqueKey(MstRoll.MST_ROLL, DSL.name("KEY_mst_roll_PRIMARY"), new TableField[] { MstRoll.MST_ROLL.ID }, true);
    public static final UniqueKey<UserRecord> KEY_USER_ID_UNIQUE = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_id_UNIQUE"), new TableField[] { User.USER.ID }, true);
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_PRIMARY"), new TableField[] { User.USER.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserRecord, MstRollRecord> USER_ROLL = Internal.createForeignKey(User.USER, DSL.name("user_roll"), new TableField[] { User.USER.ROLL_ID_FK }, Keys.KEY_MST_ROLL_PRIMARY, new TableField[] { MstRoll.MST_ROLL.ID }, true);
}
