/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.MstRoll;
import com.example.jooq.tables.User;


/**
 * Convenience access to all tables in main.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>main.mst_roll</code>.
     */
    public static final MstRoll MST_ROLL = MstRoll.MST_ROLL;

    /**
     * The table <code>main.user</code>.
     */
    public static final User USER = User.USER;
}
