/*
 * This file is generated by jOOQ.
 */
package com.example.infrastructure.jooq;


import com.example.infrastructure.jooq.tables.User;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in main.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USER_USER_ROLL_IDX = Internal.createIndex(DSL.name("user_roll_idx"), User.USER, new OrderField[] { User.USER.ROLL_ID_FK }, false);
}
