/*
 * This file is generated by jOOQ.
 */
package com.example.infrastructure.jooq;


import com.example.infrastructure.jooq.tables.Rating;
import com.example.infrastructure.jooq.tables.Review;
import com.example.infrastructure.jooq.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Main extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>main</code>
     */
    public static final Main MAIN = new Main();

    /**
     * The table <code>main.rating</code>.
     */
    public final Rating RATING = Rating.RATING;

    /**
     * The table <code>main.review</code>.
     */
    public final Review REVIEW = Review.REVIEW;

    /**
     * The table <code>main.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Main() {
        super("main", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Rating.RATING,
            Review.REVIEW,
            User.USER
        );
    }
}
