/*
 * This file is generated by jOOQ.
 */
package com.example.infrastructure.jooq;


import com.example.infrastructure.jooq.tables.MstRoll;
import com.example.infrastructure.jooq.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Main extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>main</code>
     */
    public static final Main MAIN = new Main();

    /**
     * The table <code>main.mst_roll</code>.
     */
    public final MstRoll MST_ROLL = MstRoll.MST_ROLL;

    /**
     * The table <code>main.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Main() {
        super("main", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            MstRoll.MST_ROLL,
            User.USER
        );
    }
}
