/*
 * This file is generated by jOOQ.
 */
package com.example.infrastructure.jooq;


import com.example.infrastructure.jooq.tables.Rating;
import com.example.infrastructure.jooq.tables.Review;
import com.example.infrastructure.jooq.tables.User;


/**
 * Convenience access to all tables in main.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>main.rating</code>.
     */
    public static final Rating RATING = Rating.RATING;

    /**
     * The table <code>main.review</code>.
     */
    public static final Review REVIEW = Review.REVIEW;

    /**
     * The table <code>main.user</code>.
     */
    public static final User USER = User.USER;
}
