version: "3"
services:
  web:
    build: ./web
    image: nuxt_nginx
    ports:
      - 80:80
    depends_on:
      - app
  app:
    build: ./app
    image: spring_boot
    depends_on:
      - db
    environment:
      - DB_PASSWORD=#sample1234
      - DB_HOST=db
  db:
    build: ./db
    image: sample_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=#sample1234
      - MYSQL_DATABASE=main
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d