version: "3"
services:
  # ALBの代替コンテナ
  lb:
    build: ./lb
    image: lb
    container_name: lb
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - contents
    volumes:
      - ./logs/lb:/var/log/nginx
  # S3の代替コンテナ
  contents:
    build: ./contents
    image: contents
    container_name: contents
    volumes:
      - ./nuxt-src/dist/:/usr/share/nginx/html/
  app:
    build: ./app
    image: app
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password1234
    volumes:
      - ./app/spring-boot-src/build/libs/spring-boot-src-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/app.war
      - ./logs/app:/usr/local/tomcat/logs
  db:
    build: ./db
    image: sample_db
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password1234
      - MYSQL_DATABASE=main
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
    # dbの起動を待ってから依存コンテナを起動
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s