/*
 * This file is generated by jOOQ.
 */
package com.example.infrastructure.jooq;


import com.example.infrastructure.jooq.tables.Rating;
import com.example.infrastructure.jooq.tables.Review;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in main.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index RATING_REVIEW_ID_FK_IDX = Internal.createIndex(DSL.name("review_id_fk_idx"), Rating.RATING, new OrderField[] { Rating.RATING.REVIEW_ID }, false);
    public static final Index RATING_USER_ID_FK_IDX = Internal.createIndex(DSL.name("user_id_fk_idx"), Rating.RATING, new OrderField[] { Rating.RATING.USER_ID }, false);
    public static final Index REVIEW_USER_ID_FK_IDX = Internal.createIndex(DSL.name("user_id_fk_idx"), Review.REVIEW, new OrderField[] { Review.REVIEW.USER_ID }, false);
}
