/*
 * This file is generated by jOOQ.
 */
package com.example.infrastructure.jooq.tables.records;


import com.example.infrastructure.jooq.tables.MstRoll;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MstRollRecord extends UpdatableRecordImpl<MstRollRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>main.mst_roll.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>main.mst_roll.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>main.mst_roll.label</code>.
     */
    public void setLabel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>main.mst_roll.label</code>.
     */
    public String getLabel() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MstRoll.MST_ROLL.ID;
    }

    @Override
    public Field<String> field2() {
        return MstRoll.MST_ROLL.LABEL;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLabel();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLabel();
    }

    @Override
    public MstRollRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MstRollRecord value2(String value) {
        setLabel(value);
        return this;
    }

    @Override
    public MstRollRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MstRollRecord
     */
    public MstRollRecord() {
        super(MstRoll.MST_ROLL);
    }

    /**
     * Create a detached, initialised MstRollRecord
     */
    public MstRollRecord(Integer id, String label) {
        super(MstRoll.MST_ROLL);

        setId(id);
        setLabel(label);
    }
}
