spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/main?useUnicode=true&characterEncoding=utf8&connectionTimeZone=SERVER&enabledTLSProtocols=TLSv1.2
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:#sample1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
