spring:
  datasource:
    url: jdbc:mysql://db:3306/main?useUnicode=true&characterEncoding=utf8&serverTimezone=JST&enabledTLSProtocols=TLSv1.2
    username: root
    password: #sample1234
    driver-class-name: com.mysql.cj.jdbc.Driver